---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: versus-config
data:
  config.yaml: {{ .Values.app.config | toYaml | indent 2 }}
  slack_message.tmpl: {{ .Values.app.slack_message | toYaml | indent 2 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: versus-incident
  labels:
    app-type: versus-incident
    app.kubernetes.io/name: versus-incident
spec:
  replicas: 2
  selector:
    matchLabels:
      app-type: versus-incident
      app.kubernetes.io/name: versus-incident
  template:
    metadata:
      labels:
        app-type: versus-incident
        app.kubernetes.io/name: versus-incident
    spec:
      volumes:
        - name: app-configs
          configMap:
            name: app-configs
      containers:
        - name: versus
          image: "{{ .Values.app.image }}"
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
        env:
          {{- range $k, $v := .Values.env }}
            {{- if $v }}
          - name: "{{ $k }}"
            value: "{{ $v }}"
            {{- end -}}
          {{- end }} 
        volumeMounts:
        - name: versus-config
          mountPath: /app/config/config.yaml
          subPath: config.yaml
        - name: versus-config
          mountPath: /app/config/slack_message.tmpl
          subPath: slack_message.tmpl
      volumes:
      - name: versus-config
        configMap:
          name: versus-config
---
apiVersion: v1
kind: Service
metadata:
  name: versus-service
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: versus-service
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: versus-service
    app-type: versus-service
