---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: versus-config
binaryData:
  config.yaml: {{ .Values.app.config | b64enc }}
  email_message.tmpl: {{ .Values.app.email_message | b64enc }}
  slack_message.tmpl: {{ .Values.app.slack_message | b64enc }}

---
apiVersion: v1
kind: Service
metadata:
  name: versus-service
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: versus-service
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: versus-incident
    app-type: versus-incident

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "versus-incident"
  labels:
    "app-type": "versus-incident"
    "app.kubernetes.io/name": "versus-incident"
spec:
  replicas: 1
  selector:
    matchLabels:
      "app-type": "versus-incident"
      "app.kubernetes.io/name": "versus-incident"
  template:
    metadata:
      labels:
        "app-type": "versus-incident"
        "app.kubernetes.io/name": "versus-incident"
    spec:
      volumes:
        - name: app-configs
          configMap:
            name: app-configs
      containers:
        - name: versus
          image: "{{ .Values.app.image }}"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          env:
            - name: "PORT"
              value: "3000"
            - name: "EMAIL_TEMPLATE_PATH"
              value: "config/email_message.tmpl"
            {{- range $k, $v := .Values.env }}
              {{- if $v }}
            - name: "{{ $k }}"
              value: "{{ $v }}"
              {{- end -}}
            {{- end }} 
          volumeMounts:
            - name: versus-config
              mountPath: /app/config/config.yaml
              subPath: config.yaml
            - name: versus-config
              mountPath: /app/config/slack_message.tmpl
              subPath: slack_message.tmpl
            - name: versus-config
              mountPath: /app/config/email_message.tmpl
              subPath: email_message.tmpl
      volumes:
      - name: versus-config
        configMap:
          name: versus-config