apiVersion: v2
description: NodeJS E-commerce Platform
home: https://unifie-cloud.github.io/charts/helm/evershop/
icon: https://avatars.githubusercontent.com/u/83757778?s=48&v=4
keywords:
  - ecommerce
  - shop
  - postgresql
  - react
maintainers:
  - email: Levhav@yandex.ru
    name: VictorTrapenok
name: evershop
sources:
  - https://unifie-cloud.github.io/charts/helm/evershop/
version: "1.0"
